version: "3"
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users

  post-service:
    build: ./post-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/posts

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
